/*-
 * =================================LICENSE_START==================================
 * just-json
 * ====================================SECTION=====================================
 * Copyright (C) 2024 Andy Boothe
 * ====================================SECTION=====================================
 * This is free and unencumbered software released into the public domain.
 * 
 * Anyone is free to copy, modify, publish, use, compile, sell, or
 * distribute this software, either in source code form or as a compiled
 * binary, for any purpose, commercial or non-commercial, and by any
 * means.
 * 
 * In jurisdictions that recognize copyright laws, the author or authors
 * of this software dedicate any and all copyright interest in the
 * software to the public domain. We make this dedication for the benefit
 * of the public at large and to the detriment of our heirs and
 * successors. We intend this dedication to be an overt act of
 * relinquishment in perpetuity of all present and future rights to this
 * software under copyright law.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 * 
 * For more information, please refer to <https://unlicense.org/>
 * ==================================LICENSE_END===================================
 */
package com.sigpwned.just.json;

import java.io.File;
import java.nio.file.Files;
import java.util.Objects;

/**
 * <p>
 * This class runs the "y_" (valid JSON) and "n_" (invalid JSON) tests cases from JSONTestSuite test
 * cases. (It does not run the "i_", or implementation-defined, cases.) After running each test
 * case, it prints the test case name and result (PASS or FAIL). The specific output format is
 * significant because the generate-junit-tests.py script relies on it to generate JUnit tests based
 * on the rule outcomes.
 * </p>
 * 
 * <p>
 * The maintainer uses this script to choose the coverage profile of the parser. He runs this script
 * to determine which test cases pass and which fail, then reviews the failed test cases to decide
 * whether or not to modify the parser to pass them. Running this application is only necessary when
 * updating the coverage profile.
 * </p>
 * 
 * <p>
 * Once the maintainer has reviewed the failed test cases and made any necessary changes to the
 * parser, he runs the generate-junit-tests.py script against the output of this application to
 * generate JUnit tests based on the coverage profile, and copies the generated code into
 * {@link JustJsonTestSuiteTests}. See the generate-junit-tests.py script for more information.
 * </p>
 */
public class JsonTestSuiteRunner {
  public static class TestResults {
    private final int passed;
    private final int failed;

    public TestResults(int passed, int failed) {
      if (passed < 0)
        throw new IllegalArgumentException("passed must be non-negative");
      if (failed < 0)
        throw new IllegalArgumentException("failed must be non-negative");
      this.passed = passed;
      this.failed = failed;
    }

    public int passed() {
      return passed;
    }

    public int failed() {
      return failed;
    }

    public int total() {
      return passed + failed;
    }

    public TestResults plus(TestResults other) {
      return new TestResults(passed + other.passed, failed + other.failed);
    }

    @Override
    public int hashCode() {
      return Objects.hash(failed, passed);
    }

    @Override
    public boolean equals(Object obj) {
      if (this == obj)
        return true;
      if (obj == null)
        return false;
      if (getClass() != obj.getClass())
        return false;
      TestResults other = (TestResults) obj;
      return failed == other.failed && passed == other.passed;
    }

    @Override
    public String toString() {
      return "TestResults [passed=" + passed + ", failed=" + failed + "]";
    }
  }

  public static void main(String[] args) {
    System.out
        .println("# DO NOT EDIT! This file is automatically generated by JsonTestSuiteRunner.");

    // Run tests for both valid and invalid JSON files
    System.out.println("# BEGIN y_ tests");
    TestResults ytrs = runTests(JsonTestSuite.TestCaseType.VALID, true);
    System.out.printf("# END y_ tests passed=%d failed=%d (%.2f%% passed)\n", ytrs.passed(),
        ytrs.failed(), 100.0 * ytrs.passed() / ytrs.total());


    System.out.println("# BEGIN n_ tests");
    TestResults ntrs = runTests(JsonTestSuite.TestCaseType.INVALID, false);
    System.out.printf("# END n_ tests passed=%d failed=%d (%.2f%% passed)\n", ntrs.passed(),
        ntrs.failed(), 100.0 * ntrs.passed() / ntrs.total());

    // These are implementation-defined cases, run as desired
    // runTests(JsonTestSuite.TestCaseType.IMPLEMENTATION_DECIDED, true);

    TestResults trs = ytrs.plus(ntrs);

    System.out.printf("# TOTAL tests passed=%d failed=%d (%.2f%% passed)\n", trs.passed(),
        trs.failed(), 100.0 * trs.passed() / trs.total());
  }

  private static TestResults runTests(JsonTestSuite.TestCaseType type, boolean shouldBeValid) {
    int passed = 0, failed = 0;
    for (File file : JsonTestSuite.listTestCases(type)) {
      try {
        String json = new String(Files.readAllBytes(file.toPath()));

        // We just care whether parsing succeeds or fails, not the result
        @SuppressWarnings("unused")
        Object result = JustJson.parseDocument(json);

        if (!shouldBeValid) {
          System.out.println("FAIL (expected failure, but succeeded): " + file.getName());
          failed = failed + 1;
        } else {
          System.out.println("PASS: " + file.getName());
          passed = passed + 1;
        }
      } catch (Exception e) {
        if (shouldBeValid) {
          System.out.println("FAIL (expected success, but failed): " + file.getName());
          e.printStackTrace();
          failed = failed + 1;
        } else {
          System.out.println("PASS: " + file.getName());
          passed = passed + 1;
        }
      } catch (Error e) {
        System.out.println("FAIL (error " + e.getClass().getSimpleName() + "): " + file.getName());
        failed = failed + 1;
      }
    }
    return new TestResults(passed, failed);
  }
}
